/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynamicsoft_DsLibs_DsUtil_HighResTimer */

#ifndef _Included_com_dynamicsoft_DsLibs_DsUtil_HighResTimer
#define _Included_com_dynamicsoft_DsLibs_DsUtil_HighResTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynamicsoft_DsLibs_DsUtil_HighResTimer
 * Method:    gethrtime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynamicsoft_DsLibs_DsUtil_HighResTimer_gethrtime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
