/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynamicsoft_DsLibs_DsUtil_HighResTimer */
/*
// Windows OS
#ifdef WIN32
#include <windows.h>
#endif	// WIN32

// Solaris OS
#if defined(__SVR4)
#include <sys/time.h>
#endif	// __SVR4

// Linux OS
#if defined(__linux__)
#include <sys/time.h>
#endif	// __linux__
*/

#ifndef _Included_HighResTimer
#define _Included_HighResTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynamicsoft_DsLibs_DsUtil_HighResTimer
 * Method:    gethrtime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynamicsoft_DsLibs_DsUtil_HighResTimer_gethrtime
  (JNIEnv *, jobject);


/*
 * Class:     HighResTimer
 * Method:    usleep
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_dynamicsoft_DsLibs_DsUtil_HighResTimer_usleep
  (JNIEnv *env, jobject obj, jlong ms);

#ifdef __cplusplus
}
#endif
#endif
